#!/bin/bash

composite "Assets/Beta-Overlay.png" -geometry "152x152" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-152.png" "Pushpin/Images.xcassets/AppIconBeta.appiconset/Icon-152-beta.png"
composite "Assets/Beta-Overlay.png" -geometry "144x144" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-144.png" "Pushpin/Images.xcassets/AppIconBeta.appiconset/Icon-144-beta.png"
composite "Assets/Beta-Overlay.png" -geometry "120x120" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-120.png" "Pushpin/Images.xcassets/AppIconBeta.appiconset/Icon-120-beta.png"
composite "Assets/Beta-Overlay.png" -geometry "114x114" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-114.png" "Pushpin/Images.xcassets/AppIconBeta.appiconset/Icon-114-beta.png"
composite "Assets/Beta-Overlay.png" -geometry "100x100" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-100.png" "Pushpin/Images.xcassets/AppIconBeta.appiconset/Icon-100-beta.png"
composite "Assets/Beta-Overlay.png" -geometry "80x80" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-80.png" "Pushpin/Images.xcassets/AppIconBeta.appiconset/Icon-80-beta.png"
composite "Assets/Beta-Overlay.png" -geometry "76x76" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-76.png" "Pushpin/Images.xcassets/AppIconBeta.appiconset/Icon-76-beta.png"
composite "Assets/Beta-Overlay.png" -geometry "72x72" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-72.png" "Pushpin/Images.xcassets/AppIconBeta.appiconset/Icon-72-beta.png"
composite "Assets/Beta-Overlay.png" -geometry "60x60" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-60.png" "Pushpin/Images.xcassets/AppIconBeta.appiconset/Icon-60-beta.png"
composite "Assets/Beta-Overlay.png" -geometry "58x58" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-58.png" "Pushpin/Images.xcassets/AppIconBeta.appiconset/Icon-58-beta.png"
composite "Assets/Beta-Overlay.png" -geometry "57x57" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-57.png" "Pushpin/Images.xcassets/AppIconBeta.appiconset/Icon-57-beta.png"
composite "Assets/Beta-Overlay.png" -geometry "50x50" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-50.png" "Pushpin/Images.xcassets/AppIconBeta.appiconset/Icon-50-beta.png"
composite "Assets/Beta-Overlay.png" -geometry "40x40" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-40.png" "Pushpin/Images.xcassets/AppIconBeta.appiconset/Icon-40-beta.png"
composite "Assets/Beta-Overlay.png" -geometry "29x29" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-29.png" "Pushpin/Images.xcassets/AppIconBeta.appiconset/Icon-29-beta.png"

composite "Assets/Dev-Overlay.png" -geometry "152x152" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-152.png" "Pushpin/Images.xcassets/AppIconDev.appiconset/Icon-152-dev.png"
composite "Assets/Dev-Overlay.png" -geometry "144x144" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-144.png" "Pushpin/Images.xcassets/AppIconDev.appiconset/Icon-144-dev.png"
composite "Assets/Dev-Overlay.png" -geometry "120x120" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-120.png" "Pushpin/Images.xcassets/AppIconDev.appiconset/Icon-120-dev.png"
composite "Assets/Dev-Overlay.png" -geometry "114x114" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-114.png" "Pushpin/Images.xcassets/AppIconDev.appiconset/Icon-114-dev.png"
composite "Assets/Dev-Overlay.png" -geometry "100x100" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-100.png" "Pushpin/Images.xcassets/AppIconDev.appiconset/Icon-100-dev.png"
composite "Assets/Dev-Overlay.png" -geometry "80x80" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-80.png" "Pushpin/Images.xcassets/AppIconDev.appiconset/Icon-80-dev.png"
composite "Assets/Dev-Overlay.png" -geometry "76x76" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-76.png" "Pushpin/Images.xcassets/AppIconDev.appiconset/Icon-76-dev.png"
composite "Assets/Dev-Overlay.png" -geometry "72x72" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-72.png" "Pushpin/Images.xcassets/AppIconDev.appiconset/Icon-72-dev.png"
composite "Assets/Dev-Overlay.png" -geometry "60x60" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-60.png" "Pushpin/Images.xcassets/AppIconDev.appiconset/Icon-60-dev.png"
composite "Assets/Dev-Overlay.png" -geometry "58x58" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-58.png" "Pushpin/Images.xcassets/AppIconDev.appiconset/Icon-58-dev.png"
composite "Assets/Dev-Overlay.png" -geometry "57x57" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-57.png" "Pushpin/Images.xcassets/AppIconDev.appiconset/Icon-57-dev.png"
composite "Assets/Dev-Overlay.png" -geometry "50x50" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-50.png" "Pushpin/Images.xcassets/AppIconDev.appiconset/Icon-50-dev.png"
composite "Assets/Dev-Overlay.png" -geometry "40x40" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-40.png" "Pushpin/Images.xcassets/AppIconDev.appiconset/Icon-40-dev.png"
composite "Assets/Dev-Overlay.png" -geometry "29x29" "Pushpin/Images.xcassets/AppIcon.appiconset/Icon-29.png" "Pushpin/Images.xcassets/AppIconDev.appiconset/Icon-29-dev.png"
