mappings:
  "Delicious Beta": "delicious_beta"
configs:
  app:
    pinboard_app_store_debug:
      info: "Pushpin/PinboardAppStore.plist"
      profile: "dd5ba893-f367-431a-895c-677065acf85d"
      entitlements: "Pushpin.entitlements"
      code_sign_identity: "iPhone Developer: Daniel Loewenherz (32S53QJB5F)"
    pinboard_app_store:
      info: "Pushpin/PinboardAppStore.plist"
      profile: "ef758106-b962-43f8-ae7e-ddcb930b9c4d"
      entitlements: "Pushpin.entitlements"
      code_sign_identity: "iPhone Distribution: Lionheart Software LLC (63553QQ62F)"
    pinboard_dev:
      info: "Pushpin/Dev-Info.plist"
      profile: "3a6325c1-3986-492c-ba77-5ff91e502cf0"
      entitlements: "Pushpin/Dev.entitlements"
      code_sign_identity: "iPhone Developer: Daniel Loewenherz (32S53QJB5F)"
    pinboard_beta:
      info: "Pushpin/Beta-Info.plist"
      profile: "f4e91b56-e108-4bcc-8deb-eebef30e2931"
      entitlements: "Pushpin/Beta.entitlements"
      code_sign_identity: "iPhone Distribution: Lionheart Software LLC (63553QQ62F)"
    delicious_app_store:
      info: "Pushpin/DeliciousAppStore.plist"
      profile: "29099fb1-0606-4967-884d-96f3d84d94b2"
      entitlements: "Pushpin.entitlements"
      code_sign_identity: "iPhone Distribution: Lionheart Software LLC (63553QQ62F)"
    delicious_dev:
      info: "Pushpin/DeliciousDebug.plist"
      profile: "45D6F4CF-F5A8-4BC7-92FE-4F506DCFF13A"
      entitlements: "Pushpin/Dev.entitlements"
      code_sign_identity: "iPhone Developer: Daniel Loewenherz (32S53QJB5F)"
    delicious_beta:
      info: "Pushpin/PushpinBeta.plist"
      profile: "dd5ba893-f367-431a-895c-677065acf85d"
      entitlements: "Pushpin/Beta.entitlements"
      code_sign_identity: "iPhone Distribution: Lionheart Software LLC (63553QQ62F)"
  read_later_extension:
    pinboard_app_store_debug:
      info: "Read Later Extension/AppStore-Info.plist"
      profile: "e025a654-80a5-4148-a99e-404a62ed0035"
      entitlements: "Pinboard/Share-AppStore.entitlements"
      code_sign_identity: "iPhone Developer: Daniel Loewenherz (32S53QJB5F)"
    pinboard_app_store:
      info: "Read Later Extension/AppStore-Info.plist"
      profile: "2a455488-c071-40b8-88d9-c723f244fb78"
      entitlements: "Pinboard/Share-AppStore.entitlements"
      code_sign_identity: "iPhone Distribution: Lionheart Software LLC (63553QQ62F)"
    pinboard_dev:
      info: "Read Later Extension/Dev-Info.plist"
      profile: "5312f80c-7253-49c0-86eb-a95adeaa41a1"
      entitlements: "Pinboard/Share-Dev.entitlements"
      code_sign_identity: "iPhone Developer: Daniel Loewenherz (32S53QJB5F)"
    pinboard_beta:
      info: "Read Later Extension/Beta-Info.plist"
      profile: "9fbcbd7b-8937-442d-9743-693f740c99e0"
      entitlements: "Pinboard/Share-Beta.entitlements"
      code_sign_identity: "iPhone Distribution: Lionheart Software LLC (63553QQ62F)"
    delicious_app_store:
      info: "Pushpin/Info.plist"
      profile: "29099fb1-0606-4967-884d-96f3d84d94b2"
      entitlements: "Pushpin.entitlements"
      code_sign_identity: "iPhone Distribution: Lionheart Software LLC (63553QQ62F)"
    delicious_dev:
      info: "Pushpin/Info.plist"
      profile: "45D6F4CF-F5A8-4BC7-92FE-4F506DCFF13A"
      entitlements: "Beta.entitlements"
      code_sign_identity: "iPhone Developer: Daniel Loewenherz (32S53QJB5F)"
    delicious_beta:
      info: "Pushpin/Info.plist"
      profile: "dd5ba893-f367-431a-895c-677065acf85d"
      entitlements: "Dev.entitlements"
      code_sign_identity: "iPhone Distribution: Lionheart Software LLC (63553QQ62F)"
  bookmark_extension:
    pinboard_app_store_debug:
      info: "Pinboard/Info-AppStore.plist"
      profile: "e4501265-682c-4424-9db8-a3cd76af8c35"
      entitlements: "Pinboard/Share-AppStore.entitlements"
      code_sign_identity: "iPhone Developer: Daniel Loewenherz (32S53QJB5F)"
    pinboard_app_store:
      info: "Pinboard/Info-AppStore.plist"
      profile: "e4501265-682c-4424-9db8-a3cd76af8c35"
      entitlements: "Pinboard/Share-AppStore.entitlements"
      code_sign_identity: "iPhone Distribution: Lionheart Software LLC (63553QQ62F)"
    pinboard_dev:
      info: "Pinboard/Info.plist"
      profile: "f2b976cb-cc25-4f18-8b46-214657ebc7b3"
      entitlements: "Pinboard/Share-Dev.entitlements"
      code_sign_identity: "iPhone Developer: Daniel Loewenherz (32S53QJB5F)"
    pinboard_beta:
      info: "Pinboard/Info-Beta.plist"
      profile: "78e5b688-de7c-4fbd-8343-fc0aec173d77"
      entitlements: "Pinboard/Share-Beta.entitlements"
      code_sign_identity: "iPhone Distribution: Lionheart Software LLC (63553QQ62F)"
    delicious_app_store:
      info: "Pushpin/Info.plist"
      profile: "29099fb1-0606-4967-884d-96f3d84d94b2"
      entitlements: "Pushpin.entitlements"
      code_sign_identity: "iPhone Distribution: Lionheart Software LLC (63553QQ62F)"
    delicious_dev:
      info: "Pushpin/Info.plist"
      profile: "45D6F4CF-F5A8-4BC7-92FE-4F506DCFF13A"
      entitlements: "Beta.entitlements"
      code_sign_identity: "iPhone Developer: Daniel Loewenherz (32S53QJB5F)"
    delicious_beta:
      info: "Pushpin/Info.plist"
      profile: "dd5ba893-f367-431a-895c-677065acf85d"
      entitlements: "Dev.entitlements"
      code_sign_identity: "iPhone Distribution: Lionheart Software LLC (63553QQ62F)"
  framework:
    pinboard_app_store_debug:
      code_sign_identity: "iPhone Developer: Daniel Loewenherz (32S53QJB5F)"
      info: "PushpinFramework/Info.plist"
    pinboard_app_store:
      code_sign_identity: "iPhone Distribution: Lionheart Software LLC (63553QQ62F)"
      info: "PushpinFramework/Info.plist"
    pinboard_dev:
      code_sign_identity: "iPhone Developer: Daniel Loewenherz (32S53QJB5F)"
      info: "PushpinFramework/Info.plist"
    pinboard_beta:
      code_sign_identity: "iPhone Distribution: Lionheart Software LLC (63553QQ62F)"
      info: "PushpinFramework/Info.plist"
    delicious_app_store:
      code_sign_identity: "iPhone Distribution: Lionheart Software LLC (63553QQ62F)"
      info: "PushpinFramework/Info.plist"
    delicious_dev:
      code_sign_identity: "iPhone Developer: Daniel Loewenherz (32S53QJB5F)"
      info: "PushpinFramework/Info.plist"
    delicious_beta:
      code_sign_identity: "iPhone Distribution: Lionheart Software LLC (63553QQ62F)"
      info: "PushpinFramework/Info.plist"
