mappings:
  "Delicious Beta": "delicious_beta"
configs:
  app:
    pinboard_app_store_debug:
      info: "Pushpin/PinboardAppStore.plist"
      profile: "e53d0bf9-2bca-48e3-bbc8-dcd071bd93d4"
      entitlements: "Pushpin.entitlements"
      code_sign_identity: ""
    pinboard_app_store:
      info: "Pushpin/PinboardAppStore.plist"
      profile: "83d22b2d-15f8-4faf-a6a6-b952b03e06d4"
      entitlements: "Pushpin.entitlements"
      code_sign_identity: ""
    pinboard_dev:
      info: "Pushpin/Dev-Info.plist"
      profile: "d70cb10f-1a66-447e-8d52-de0b6c3a2d41"
      entitlements: "Pushpin/Dev.entitlements"
      code_sign_identity: ""
    pinboard_beta:
      info: "Pushpin/Beta-Info.plist"
      profile: "bb2aa8a0-2ee3-4c17-88c0-70e31e1e8a97"
      entitlements: "Pushpin/Beta.entitlements"
      code_sign_identity: ""
    delicious_app_store:
      info: "Pushpin/DeliciousAppStore.plist"
      profile: "29099fb1-0606-4967-884d-96f3d84d94b2"
      entitlements: "Pushpin.entitlements"
      code_sign_identity: "iPhone Distribution: Lionheart Software LLC (63553QQ62F)"
    delicious_dev:
      info: "Pushpin/DeliciousDebug.plist"
      profile: "45D6F4CF-F5A8-4BC7-92FE-4F506DCFF13A"
      entitlements: "Pushpin/Dev.entitlements"
      code_sign_identity: "iPhone Developer: Daniel Loewenherz (32S53QJB5F)"
    delicious_beta:
      info: "Pushpin/PushpinBeta.plist"
      profile: "dd5ba893-f367-431a-895c-677065acf85d"
      entitlements: "Pushpin/Beta.entitlements"
      code_sign_identity: "iPhone Distribution: Lionheart Software LLC (63553QQ62F)"
  read_later_extension:
    pinboard_app_store_debug:
      info: "Read Later Extension/AppStore-Info.plist"
      profile: "ca571a44-4db4-4ce8-8bbf-1b2c0fa02201"
      entitlements: "Pinboard/Share-AppStore.entitlements"
      code_sign_identity: ""
    pinboard_app_store:
      info: "Read Later Extension/AppStore-Info.plist"
      profile: "2a455488-c071-40b8-88d9-c723f244fb78"
      entitlements: "Pinboard/Share-AppStore.entitlements"
      code_sign_identity: ""
    pinboard_dev:
      info: "Read Later Extension/Dev-Info.plist"
      profile: "5312f80c-7253-49c0-86eb-a95adeaa41a1"
      entitlements: "Pinboard/Share-Dev.entitlements"
      code_sign_identity: ""
    pinboard_beta:
      info: "Read Later Extension/Beta-Info.plist"
      profile: "134759b9-5d5f-412a-a292-c5bad5fbb77a"
      entitlements: "Pinboard/Share-Beta.entitlements"
      code_sign_identity: ""
    delicious_app_store:
      info: "Pushpin/Info.plist"
      profile: "29099fb1-0606-4967-884d-96f3d84d94b2"
      entitlements: "Pinboard/Share-AppStore.entitlements"
      code_sign_identity: "iPhone Distribution: Lionheart Software LLC (63553QQ62F)"
    delicious_dev:
      info: "Pushpin/Info.plist"
      profile: "45D6F4CF-F5A8-4BC7-92FE-4F506DCFF13A"
      entitlements: "Pinboard/Share-Dev.entitlements"
      code_sign_identity: "iPhone Developer: Daniel Loewenherz (32S53QJB5F)"
    delicious_beta:
      info: "Pushpin/Info.plist"
      profile: "dd5ba893-f367-431a-895c-677065acf85d"
      entitlements: "Pinboard/Share-Beta.entitlements"
      code_sign_identity: "iPhone Distribution: Lionheart Software LLC (63553QQ62F)"
  bookmark_extension:
    pinboard_app_store_debug:
      info: "Pinboard/Info-AppStore.plist"
      profile: "d9cc841f-ed81-4a78-a7c3-5afde420c4d2"
      entitlements: "Pinboard/Share-AppStore.entitlements"
      code_sign_identity: ""
    pinboard_app_store:
      info: "Pinboard/Info-AppStore.plist"
      profile: "1a8e10b3-a32a-4e2e-8fae-6facfe097d90"
      entitlements: "Pinboard/Share-AppStore.entitlements"
      code_sign_identity: ""
    pinboard_dev:
      info: "Pinboard/Info.plist"
      profile: "f2b976cb-cc25-4f18-8b46-214657ebc7b3"
      entitlements: "Pinboard/Share-Dev.entitlements"
      code_sign_identity: ""
    pinboard_beta:
      info: "Pinboard/Info-Beta.plist"
      profile: "66962d6b-1872-471f-9dab-077db895d09b"
      entitlements: "Pinboard/Share-Beta.entitlements"
      code_sign_identity: ""
    delicious_app_store:
      info: "Pushpin/Info.plist"
      profile: "29099fb1-0606-4967-884d-96f3d84d94b2"
      entitlements: "Pinboard/Share-AppStore.entitlements"
      code_sign_identity: "iPhone Distribution: Lionheart Software LLC (63553QQ62F)"
    delicious_dev:
      info: "Pushpin/Info.plist"
      profile: "45D6F4CF-F5A8-4BC7-92FE-4F506DCFF13A"
      entitlements: "Pinboard/Share-Dev.entitlements"
      code_sign_identity: "iPhone Developer: Daniel Loewenherz (32S53QJB5F)"
    delicious_beta:
      info: "Pushpin/Info.plist"
      profile: "dd5ba893-f367-431a-895c-677065acf85d"
      entitlements: "Pinboard/Share-Beta.entitlements"
      code_sign_identity: "iPhone Distribution: Lionheart Software LLC (63553QQ62F)"
  framework:
    pinboard_app_store_debug:
      code_sign_identity: "iPhone Developer: Daniel Loewenherz (32S53QJB5F)"
      info: "PushpinFramework/Info.plist"
    pinboard_app_store:
      code_sign_identity: "iPhone Distribution: Lionheart Software LLC (63553QQ62F)"
      info: "PushpinFramework/Info.plist"
    pinboard_dev:
      code_sign_identity: "iPhone Developer: Daniel Loewenherz (32S53QJB5F)"
      info: "PushpinFramework/Info.plist"
    pinboard_beta:
      code_sign_identity: "iPhone Distribution: Lionheart Software LLC (63553QQ62F)"
      info: "PushpinFramework/Info.plist"
    delicious_app_store:
      code_sign_identity: "iPhone Distribution: Lionheart Software LLC (63553QQ62F)"
      info: "PushpinFramework/Info.plist"
    delicious_dev:
      code_sign_identity: "iPhone Developer: Daniel Loewenherz (32S53QJB5F)"
      info: "PushpinFramework/Info.plist"
    delicious_beta:
      code_sign_identity: "iPhone Distribution: Lionheart Software LLC (63553QQ62F)"
      info: "PushpinFramework/Info.plist"
