platform :ios, '7'

pod 'TestFlightSDK', '2.1.1-beta'
pod 'Reachability', '3.0.0'
pod 'PocketAPI', '1.0.2'
pod 'FMDB', '2.1'
pod 'KeychainItemWrapper', '1.2'
pod 'TTTAttributedLabel', '1.7.1'
pod 'Mixpanel', '2.0.0'
# pod 'uservoice-iphone-sdk', '2.0.13'
pod 'uservoice-iphone-sdk', :podspec => 'Specs/uservoice-iphone-sdk.podspec'
pod 'LHSCategoryCollection', :git => 'https://github.com/lionheart/LHSCategoryCollection.git'

pod 'oauthconsumer', :podspec => 'Specs/oauthconsumer.podspec'
pod 'RPSTPasswordManagementAppService', :podspec => 'Specs/RPSTPasswordManagementAppService.podspec'
pod 'HTMLParser', :podspec => 'Specs/HTMLParser.podspec'
pod 'BloomFilter', :podspec => 'Specs/BloomFilter.podspec'
pod 'TextExpanderTouchSDK', :podspec => 'Specs/TextExpanderTouchSDK.podspec'
