platform :ios, '7'

inhibit_all_warnings!

pod 'TestFlightSDK', '2.2.1'
pod 'Reachability', '3.0.0'
pod 'PocketAPI', '1.0.2'
pod 'FMDB', '2.1'
pod 'KeychainItemWrapper', '1.2'
pod 'TTTAttributedLabel', '1.8.0'
# pod 'Mixpanel', '2.0.0'
pod 'uservoice-iphone-sdk', '3.0.1'
pod 'LHSCategoryCollection', :local => '../LHSCategoryCollection'
pod 'LHSFMDatabaseAdditions', :podspec => 'Specs/LHSFMDatabaseAdditions.podspec'
pod 'LHSCustomTransitionCollection', :local => '../LHSCustomTransitionCollection'
pod 'LHDelicious', :local => '../LHDelicious'
pod 'oauthconsumer', :podspec => 'Specs/oauthconsumer.podspec'
pod 'RPSTPasswordManagementAppService', :podspec => 'Specs/RPSTPasswordManagementAppService.podspec'
pod 'HTMLParser', :podspec => 'Specs/HTMLParser.podspec'
pod 'TextExpander', '2.3.1'
pod 'MWFeedParser', '1.0.0'
pod 'ADNActivityCollection', :podspec => 'Specs/ADNActivityCollection.podspec'
pod 'ASPinboard', :local => 'Vendor/ASPinboard'
pod 'OpenInChrome', '0.0.1'
