platform :ios, '7'

inhibit_all_warnings!

pod 'TestFlightSDK', '2.2.0-beta'
pod 'Reachability', '3.0.0'
pod 'PocketAPI', '1.0.2'
pod 'FMDB', '2.1'
pod 'KeychainItemWrapper', '1.2'
pod 'TTTAttributedLabel', '1.8.0'
pod 'Mixpanel', '2.0.0'
pod 'uservoice-iphone-sdk', '3.0'
# pod 'uservoice-iphone-sdk', :podspec => 'Specs/uservoice-iphone-sdk.podspec'
pod 'LHSCategoryCollection', :local => '../LHSCategoryCollection'
pod 'LHSCustomTransitionCollection', :local => '../LHSCustomTransitionCollection'
pod 'oauthconsumer', :podspec => 'Specs/oauthconsumer.podspec'
pod 'RPSTPasswordManagementAppService', :podspec => 'Specs/RPSTPasswordManagementAppService.podspec'
pod 'HTMLParser', :podspec => 'Specs/HTMLParser.podspec'
pod 'TextExpanderTouchSDK', :podspec => 'Specs/TextExpanderTouchSDK.podspec'
# pod 'hpple', :podspec => 'Specs/hpple.podspec'
pod 'MWFeedParser', '1.0.0'
