#!/bin/sh

# Chooses the info.plist with the higher bundle version

# $1 => file at ancestor of both commits
# $2 => current file
# $3 => proposed change to file

TWO=`/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$2"`
THREE=`/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$3"`

if [ "$THREE" -gt "$TWO" ]; then
  cp $3 $2
fi

exit 0
