#!/bin/bash

convert "Pinboard.appiconset/AppStore-512.png" -draw "image over 0,0 512,512 'Beta-Overlay.png'" "PinboardBeta.appiconset/AppStore-512.png"
convert "Pinboard.appiconset/AppStore-512@2x.png" -draw "image over 0,0 512,512 'Beta-Overlay.png'" "PinboardBeta.appiconset/AppStore-512@2x.png"
convert "Pinboard.appiconset/iPad-76.png" -draw "image over 0,0 76,76 'Beta-Overlay.png'" "PinboardBeta.appiconset/iPad-76.png"
convert "Pinboard.appiconset/iPad-76@2x.png" -draw "image over 0,0 76,76 'Beta-Overlay.png'" "PinboardBeta.appiconset/iPad-76@2x.png"
convert "Pinboard.appiconset/iPadSettings-29.png" -draw "image over 0,0 29,29 'Beta-Overlay.png'" "PinboardBeta.appiconset/iPadSettings-29.png"
convert "Pinboard.appiconset/iPadSettings-29@2x.png" -draw "image over 0,0 29,29 'Beta-Overlay.png'" "PinboardBeta.appiconset/iPadSettings-29@2x.png"
convert "Pinboard.appiconset/iPadSpotlight-40@2x.png" -draw "image over 0,0 40,40 'Beta-Overlay.png'" "PinboardBeta.appiconset/iPadSpotlight-40@2x.png"
convert "Pinboard.appiconset/iPhone-60@2x.png" -draw "image over 0,0 60,60 'Beta-Overlay.png'" "PinboardBeta.appiconset/iPhone-60@2x.png"
convert "Pinboard.appiconset/iPhoneSettings-29.png" -draw "image over 0,0 29,29 'Beta-Overlay.png'" "PinboardBeta.appiconset/iPhoneSettings-29.png"
convert "Pinboard.appiconset/iPhoneSettings-29@2x.png" -draw "image over 0,0 29,29 'Beta-Overlay.png'" "PinboardBeta.appiconset/iPhoneSettings-29@2x.png"
convert "Pinboard.appiconset/iPhoneSpotlight-40.png" -draw "image over 0,0 40,40 'Beta-Overlay.png'" "PinboardBeta.appiconset/iPhoneSpotlight-40.png"
convert "Pinboard.appiconset/iPhoneSpotlight-40@2x.png" -draw "image over 0,0 40,40 'Beta-Overlay.png'" "PinboardBeta.appiconset/iPhoneSpotlight-40@2x.png"

convert "Pinboard.appiconset/AppStore-512.png" -draw "image over 0,0 512,512 'Dev-Overlay.png'" "PinboardDev.appiconset/AppStore-512.png"
convert "Pinboard.appiconset/AppStore-512@2x.png" -draw "image over 0,0 512,512 'Dev-Overlay.png'" "PinboardDev.appiconset/AppStore-512@2x.png"
convert "Pinboard.appiconset/iPad-76.png" -draw "image over 0,0 76,76 'Dev-Overlay.png'" "PinboardDev.appiconset/iPad-76.png"
convert "Pinboard.appiconset/iPad-76@2x.png" -draw "image over 0,0 76,76 'Dev-Overlay.png'" "PinboardDev.appiconset/iPad-76@2x.png"
convert "Pinboard.appiconset/iPadSettings-29.png" -draw "image over 0,0 29,29 'Dev-Overlay.png'" "PinboardDev.appiconset/iPadSettings-29.png"
convert "Pinboard.appiconset/iPadSettings-29@2x.png" -draw "image over 0,0 29,29 'Dev-Overlay.png'" "PinboardDev.appiconset/iPadSettings-29@2x.png"
convert "Pinboard.appiconset/iPadSpotlight-40@2x.png" -draw "image over 0,0 40,40 'Dev-Overlay.png'" "PinboardDev.appiconset/iPadSpotlight-40@2x.png"
convert "Pinboard.appiconset/iPhone-60@2x.png" -draw "image over 0,0 60,60 'Dev-Overlay.png'" "PinboardDev.appiconset/iPhone-60@2x.png"
convert "Pinboard.appiconset/iPhoneSettings-29.png" -draw "image over 0,0 29,29 'Dev-Overlay.png'" "PinboardDev.appiconset/iPhoneSettings-29.png"
convert "Pinboard.appiconset/iPhoneSettings-29@2x.png" -draw "image over 0,0 29,29 'Dev-Overlay.png'" "PinboardDev.appiconset/iPhoneSettings-29@2x.png"
convert "Pinboard.appiconset/iPhoneSpotlight-40.png" -draw "image over 0,0 40,40 'Dev-Overlay.png'" "PinboardDev.appiconset/iPhoneSpotlight-40.png"
convert "Pinboard.appiconset/iPhoneSpotlight-40@2x.png" -draw "image over 0,0 40,40 'Dev-Overlay.png'" "PinboardDev.appiconset/iPhoneSpotlight-40@2x.png"
