# vim: set ft=ruby:

fastlane_version "2.66.2"
xcode_select "/Applications/Xcode.app"
default_platform :ios

project_file = "Pushpin.xcodeproj"

platform :ios do
  lane :beta do
    gym
    deliver
  end

  lane :appstore do
    ensure_git_status_clean
    increment_build_number(xcodeproj: project_file)
    version_number = get_version_number(xcodeproj: project_file, target: "Pushpin")
    build_number = get_build_number(xcodeproj: project_file)
    commit_version_bump(message: "bump to #{build_number}", xcodeproj: "./#{project_file}")

    gym

    ENV["SCHEME"] = "Pushpin"
    # snapshot
    deliver

    add_git_tag tag: "v#{version_number}+#{build_number}"
    push_to_git_remote
  end
end
