# vim: set ft=ruby:

fastlane_version "2.66.2"
xcode_select "/Applications/Xcode.app"
default_platform :ios

project_file = "Pushpin.xcodeproj"

platform :ios do
  lane :beta do
    gym
    deliver
  end

  lane :appstore do
    ensure_git_status_clean

    # Set the build number to the # + full date.
    raw_build_number = get_build_number(xcodeproj: project_file)
    dt = Time.new.strftime("%Y.%m.%d")
    build_number = Integer(raw_build_number.split(".")[0])

    increment_build_number(build_number: "#{build_number+1}.#{dt}", xcodeproj: project_file)

    gym

    ENV["SCHEME"] = "Pushpin"

    # snapshot
    deliver

    version_number = get_version_number(xcodeproj: project_file, target: "Pushpin", configuration: "Release")
    commit_version_bump(message: "bump to #{build_number}", xcodeproj: project_file)
    add_git_tag tag: "v#{version_number}+#{build_number}"
    push_to_git_remote
  end
end
